update firefox-profile to 1.0.0
webdriverio/wdio-firefox-profile-service pull request #10
Opened 2017-04-17 21:10 UTC by andriilazebnyi

2017-04-17 21:18 UTC, christian-bromann requested changes
some comments

2017-04-17 21:18 UTC, christian-bromann commented on lib/firefox-profile-launch-service.js
> +                    return resolve()
it should reject the promise in case of an error

2017-04-17 21:18 UTC, christian-bromann commented on package.json
> +    "firefox-profile": "^1.0.0"
let's specify version with `~1.0.0` just to be safe

2017-04-17 21:23 UTC, andriilazebnyi commented
@christian-bromann Thanks. Fixed.

2017-04-17 21:31 UTC, christian-bromann requested changes

2017-04-17 21:31 UTC, christian-bromann commented on lib/firefox-profile-launch-service.js
> +                    return reject()
reject is not defined, please define it

2017-04-17 21:50 UTC, christian-bromann commented
@andriilazebnyi there is still a linting error

2017-04-17 22:00 UTC, andriilazebnyi commented
@christian-bromann Looks like VSCode eslint plugin didn't catch it. Fixed.

2017-05-07 14:30 UTC, christian-bromann approved these changes
👍🏻

2017-05-07 14:30 UTC, merged